name: DMFourLLIE
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - cryptography=41.0.2
  - cuda-cccl=12.2.128
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.2.128
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask-core=2023.4.1
  - dav1d=1.2.1
  - filelock=3.9.0
  - freetype=2.12.1
  - fsspec=2023.10.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.37
  - icc_rt=2022.1.0
  - imagecodecs=2023.1.23
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.3.129
  - libcurand-dev=10.3.3.129
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - networkx=3.1
  - numexpr=2.8.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.1
  - pandas=2.0.3
  - partd=1.4.1
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - pooch=1.7.0
  - psutil=5.9.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - requests=2.31.0
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - toolz=0.12.0
  - typing_extensions=4.7.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - xz=5.4.2
  - yaml=0.2.5
  - zfp=1.0.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - chardet==3.0.4
      - contourpy==1.1.1
      - dominate==2.9.1
      - einops==0.7.0
      - eval-type-backport==0.2.0
      - flatbuffers==23.5.26
      - fonttools==4.42.1
      - ftfy==6.1.1
      - future==0.18.3
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grad-cam==1.5.0
      - grpcio==1.57.0
      - h5py==3.11.0
      - idna==2.7
      - imageio==2.31.1
      - imgaug==0.4.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - ipaddress==1.0.23
      - joblib==1.3.2
      - keras==2.13.1
      - kiwisolver==1.4.5
      - kornia==0.7.0
      - lazy-loader==0.3
      - libclang==16.0.6
      - lmdb==1.4.1
      - lpips==0.1.4
      - markdown==3.4.4
      - matplotlib==3.7.3
      - niqe==0.1.1
      - nms==0.1.6
      - numpy==1.24.4
      - oauthlib==3.2.2
      - openai-clip==1.0.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.3.0
      - protobuf==4.24.3
      - ptflops==0.7
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyiqa==0.1.8
      - pyparsing==3.1.1
      - pytorch-msssim==1.0.0
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - shapely==2.0.2
      - sklearn==0.0.post9
      - tb-nightly==2.14.0a20230808
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.2.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==1.1.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - timm==0.4.12
      - tomli==2.0.1
      - torchaudio==2.0.2
      - torchfile==0.1.0
      - torchsummaryx==1.3.0
      - torchvision==0.15.2
      - tqdm==4.66.1
      - ttach==0.0.3
      - typing-extensions==4.12.2
      - ultralytics==8.1.42
      - urllib3==1.24.3
      - wcwidth==0.2.9
      - werkzeug==2.3.7
      - wrapt==1.15.0
      - yacs==0.1.8
      - yapf==0.40.1
      - zipp==3.16.2

